name: facelytical
description: Face detection and capture library for Flutter
version: 0.0.1
homepage: https://github.com/NightingaleNath/facelytical_flutter

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  google_mlkit_face_detection: ^0.13.1
  permission_handler: ^11.4.0
  image: ^4.5.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
